### ISSUE TITLE
default cartocss

### ISSUE THREAD

**Issue by makella** [CartoDB/labs-colorscales#16]
hi abel!

is it possible to have the default cartocss for polygons like this when a cartocolor palette is used? Basically where the `polygon-opacity` is set to `0.9` and the line color is a slightly lighter version of the fill with some additional line properties?

```
#table { 
 polygon-opacity: 0.9; 
 line-opacity: 1;
 line-width: 0.5; 

 [ total_pop > 3961 ]{ 
  polygon-fill: @color0;
  line-color: lighten(@color0,5);  
 } 
 ...
}
```
thanks!
mamata

**Comment by AbelVM** [comment]
Fixed in v0.11
