### ISSUE TITLE
default cartocss: markers

### ISSUE THREAD

**Issue by makella** [CartoDB/labs-colorscales#18]
hi abel!

can you add `marker-allow-overlap: true;` to the default marker cartocss.

also, can you make the default cartocss for markers like this:

```
#layer {
  marker-fill-opacity: 0.9;
  marker-line-color: #FFFFFF;
  marker-line-width: 1;
  marker-line-opacity: 0.9;
  marker-width: 8;
  marker-fill: #d3d3d3;
  marker-allow-overlap: true;

  [ accommodates <= 16] {
    marker-fill: @5;
    marker-line-color: darken(@5,5);
  }
}
```
Basically, change the size, opacity, and similar to polygons use a darker version of the color for the outline.

thanks soooo much!!
mamata

**Comment by AbelVM** [comment]
Added in v0.12
